### ISSUE TITLE
gvim not found, make sure you started atom from the terminal and that gvim is on the PATH

### ISSUE THREAD

**Issue by seven-dev** [mattn/open-vim#3] opened 2015-09-18 14:05 UTC
Hello,

I have gvim on the path and I started atom from the command line (on Windows). On windows I think that "which" command should be "where".

```
exec "which #{vimType}", (error, stdout, stderr) =>
```

Thank you.

**Comment by fgrsnau** [comment] 2015-11-10 09:34
I want to reopen this issue, because the current fix breaks the package on Linux.

The current code reads: `whichType = if OS.platform() is "win32" then "which" else "where"`

The problem is that it should be exactly the other way around: `whichType = if OS.platform() is "win32" then "where" else "which"`

**Comment by mattn** [comment] 2015-11-10 09:46
Ah, right. But currently I don't install atom. Could you please send me pull-request?

**Comment by oxo42** [comment] 2016-02-12 10:31
Just a note.  This is closed by pull request #5

**Comment by mattn** [comment] 2016-02-12 10:35
thanks

**Closed as completed by mattn** 2016-02-12 10:34 UTC
